title: "吾月"
subtitle: "何夜无月，逝者如斯"
baseurl: "http://moonye.me/"

languageCode: "zh-cn"
defaultContentLanguage: "zh-cn"
hasCJKLanguage: true

Paginate: 5

metaDataFormat: "yaml"
theme: "moony"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
  project: "projects"

params:
  dateformat: "2006-01-02 15:04" # Optional
