title: "吾月"
subtitle: "何夜无月，逝者如斯"
baseurl: "http://moonye.me"

languageCode: "zh-cn"
defaultContentLanguage: "zh-cn"
hasCJKLanguage: true

metaDataFormat: "yaml"
theme: "moony"

menu:
  主页:
      - Name: "主页"
        URL: "/"
        weight: 1
      - Name: "文章"
        URL: "/archives/"
        weight: 2
      - Name: "简介"
        URL: "/about/"
        weight: 3

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
  project: "projects"

params:
  dateformat: "Jan 2, 2006" # Optional
